# Generated by Django 4.2 on 2025-01-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('posts', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='files.asset'),
            preserve_default=False,
        ),
    ]
