# Generated by Django 4.2 on 2025-01-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postimage_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
    ]
