# Generated by Django 4.2 on 2025-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='roles/icons/'),
        ),
    ]
