# Generated by Django 4.2 on 2025-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_asset_content_type_remove_asset_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
