# Generated by Django 4.2 on 2025-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_favoritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='post_category_icons/'),
        ),
    ]
