# Generated by Django 4.2 on 2025-02-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='unit_price',
            field=models.CharField(blank=True, choices=[('Toman', 'IRT'), ('Rial', 'IRR')], default='Toman', max_length=10, null=True),
        ),
    ]
